In [1]:
import pandas as pd
import numpy as np

In [2]:
raw = pd.read_csv('data/Base.csv')
raw.head(5)

,fraud_bool,income,name_email_similarity,prev_address_months_count,current_address_months_count,customer_age,days_since_request,intended_balcon_amount,payment_type,zip_count_4w,...,has_other_cards,proposed_credit_limit,foreign_request,source,session_length_in_minutes,device_os,keep_alive_session,device_distinct_emails_8w,device_fraud_count,month
0,0,0.3,0.986506,-1,25,40,0.006735,102.453711,AA,1059,...,0,1500.0,0,INTERNET,16.224843,linux,1,1,0,0
1,0,0.8,0.617426,-1,89,20,0.010095,-0.849551,AD,1658,...,0,1500.0,0,INTERNET,3.363854,other,1,1,0,0
2,0,0.8,0.996707,9,14,40,0.012316,-1.490386,AB,1095,...,0,200.0,0,INTERNET,22.730559,windows,0,1,0,0
3,0,0.6,0.475100,11,14,30,0.006991,-1.863101,AB,3483,...,0,200.0,0,INTERNET,15.215816,linux,1,1,0,0
4,0,0.9,0.842307,-1,29,40,5.742626,47.152498,AA,2339,...,0,200.0,0,INTERNET,3.743048,other,0,1,0,0

In [3]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 32 columns):
 #   Column                            Non-Null Count    Dtype
---  ------                            --------------    -----
 0   fraud_bool                        1000000 non-null  int64
 1   income                            1000000 non-null  float64
 2   name_email_similarity             1000000 non-null  float64
 3   prev_address_months_count         1000000 non-null  int64
 4   current_address_months_count      1000000 non-null  int64
 5   customer_age                      1000000 non-null  int64
 6   days_since_request                1000000 non-null  float64
 7   intended_balcon_amount            1000000 non-null  float64
 8   payment_type                      1000000 non-null  object
 9   zip_count_4w                      1000000 non-null  int64
 10  velocity_6h                       1000000 non-null  float64
 11  velocity_24h                      1000000 non-null  float64
 12  velocity_4w                       1000000 non-null  float64
 13  bank_branch_count_8w              1000000 non-null  int64
 14  date_of_birth_distinct_emails_4w  1000000 non-null  int64
 15  employment_status                 1000000 non-null  object
 16  credit_risk_score                 1000000 non-null  int64
 17  email_is_free                     1000000 non-null  int64
 18  housing_status                    1000000 non-null  object
 19  phone_home_valid                  1000000 non-null  int64
 20  phone_mobile_valid                1000000 non-null  int64
 21  bank_months_count                 1000000 non-null  int64
 22  has_other_cards                   1000000 non-null  int64
 23  proposed_credit_limit             1000000 non-null  float64
 24  foreign_request                   1000000 non-null  int64
 25  source                            1000000 non-null  object
 26  session_length_in_minutes         1000000 non-null  float64
 27  device_os                         1000000 non-null  object
 28  keep_alive_session                1000000 non-null  int64
 29  device_distinct_emails_8w         1000000 non-null  int64
 30  device_fraud_count                1000000 non-null  int64
 31  month                             1000000 non-null  int64
dtypes: float64(9), int64(18), object(5)
memory usage: 244.1+ MB

In [4]:
def to_nan(feature_list):
    for feature in feature_list:
        raw[feature] = raw[feature].apply(lambda x: x if x >= 0 else np.nan)

missing_features = ['prev_address_months_count', 'current_address_months_count', 'intended_balcon_amount', 'bank_months_count', 'session_length_in_minutes', 'device_distinct_emails_8w' ]
to_nan(missing_features)

In [5]:
test = raw.select_dtypes(exclude=['object'])

In [6]:
# # 변환 전 데이터 확인
# test.head(10)

# #변환
# from impyute.imputation.cs import mice
# np_imputed=mice(test.values) # mice 학습시작
# df_imputed = pd.DataFrame(np_imputed)

# # 변환 후 데이터 확인
# df_imputed.head(10)

In [7]:
from sklearn.impute import KNNImputer

In [8]:
imputer = KNNImputer(n_neighbors=2, weights="uniform")

In [9]:
test

,fraud_bool,income,name_email_similarity,prev_address_months_count,current_address_months_count,customer_age,days_since_request,intended_balcon_amount,zip_count_4w,velocity_6h,...,phone_mobile_valid,bank_months_count,has_other_cards,proposed_credit_limit,foreign_request,session_length_in_minutes,keep_alive_session,device_distinct_emails_8w,device_fraud_count,month
0,0,0.3,0.986506,NaN,25.0,40,0.006735,102.453711,1059,13096.035018,...,1,9.0,0,1500.0,0,16.224843,1,1.0,0,0
1,0,0.8,0.617426,NaN,89.0,20,0.010095,NaN,1658,9223.283431,...,1,2.0,0,1500.0,0,3.363854,1,1.0,0,0
2,0,0.8,0.996707,9.0,14.0,40,0.012316,NaN,1095,4471.472149,...,1,30.0,0,200.0,0,22.730559,0,1.0,0,0
3,0,0.6,0.475100,11.0,14.0,30,0.006991,NaN,3483,14431.993621,...,1,1.0,0,200.0,0,15.215816,1,1.0,0,0
4,0,0.9,0.842307,NaN,29.0,40,5.742626,47.152498,2339,7601.511579,...,1,26.0,0,200.0,0,3.743048,0,1.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0,0.8,0.124690,NaN,143.0,30,0.051348,NaN,530,6732.602414,...,1,31.0,0,1500.0,0,16.967770,0,1.0,0,7
999996,0,0.9,0.824544,NaN,193.0,30,0.009591,0.008307,408,1574.293294,...,1,NaN,1,1000.0,0,1.504109,0,1.0,0,7
999997,0,0.8,0.140891,NaN,202.0,10,0.059287,50.609995,749,1258.864938,...,1,31.0,0,200.0,0,16.068595,0,1.0,0,7
999998,0,0.9,0.002480,52.0,3.0,30,0.023357,NaN,707,7048.137128,...,1,1.0,0,200.0,0,1.378683,1,1.0,0,7
999999,0,0.6,0.993391,NaN,174.0,30,0.020422,14.942456,655,3737.076479,...,1,15.0,1,200.0,0,1.947926,1,1.0,0,7

In [10]:
test_imputation = pd.DataFrame(imputer.fit_transform(test.to_numpy()), columns=test.columns)

KeyboardInterrupt: